### ISSUE TITLE
can not load vlm2vec qwen2 vl with the code snippet in hf model page

### ISSUE THREAD

**Issue by Adenialzz** [TIGER-AI-Lab/VLM2Vec#44]

**Comment by memray** [comment]
@Adenialzz thanks for raising the issue.
I fixed a few bugs in the demo code and it has been pushed [here](https://github.com/TIGER-AI-Lab/VLM2Vec/blob/main/examples/qwen2vl/demo.py). However, something still seems to be off, likely due to the merged checkpoint. I need more time to check the problem. 
You may try directly loading from [LoRA](https://huggingface.co/TIGER-Lab/VLM2Vec-Qwen2VL/tree/main/lora) and see if the output is reasonable, following the logic in `eval.py`.

**Comment by Adenialzz** [comment]
Thanks a lot for your so quick response. I tested `demo.py` but still get many params mismatch and wrong results:

```
A cat and a dog = tensor([[-0.0352]], device='cuda:0', dtype=torch.bfloat16,
       grad_fn=<MmBackward0>)
A cat and a tiger = tensor([[-0.0118]], device='cuda:0', dtype=torch.bfloat16,
       grad_fn=<MmBackward0>)
```

Is there anywhere I did wrong ?

**Comment by Adenialzz** [comment]
According to the mismatched parameters, I also think it is a problem caused by lora fusion.

**Comment by memray** [comment]
@Adenialzz can you try loaing from original Qwen2VL then the LoRA adapter and see if the similarity looks correct? I don't think I can look into it recently.

**Comment by Adenialzz** [comment]
OK, I'll check it myself. Thanks.

**Comment by Adenialzz** [comment]
I got close result on mmeb-eval benchmark with loading original qwen2vl model and patching vlm2vec lora into it. Thanks for your guidance.
